### ISSUE TITLE
v1.1.7-补丁-1 安装了，也加载，就是抖音打不开，麻烦大佬看看，谢谢！

### ISSUE THREAD

**Issue by berebrn** [GangJust/FreedomPlus#10]
![Screenshot_2023-08-07-15-37-29-521_com freegang fplus](https://github.com/GangJust/FreedomPlus/assets/140738041/a69313ee-7dd1-414f-b584-b5fc1f896ea0)
![Screenshot_2023-08-07-09-42-36-603_com fankes apperrorstracking](https://github.com/GangJust/FreedomPlus/assets/140738041/91ed28bc-1c24-4dc1-8be8-c2567724e067)
报错如下：
Generated by AppErrorsTracking
Project Url: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: MI 6
[Display]: NMF26X
[Android Version]: 7.1.1
[Android API Level]: 25
[System Locale]: zh_CN
[Process ID]: 4492
[CPU ABI]: arm64-v8a
[Package Name]: com.ss.android.ugc.aweme
[Version Name]: 26.0.0
[Version Code]: 260001
[Error Type]: Native
[Crash Time]: 2023-08-07T15:39:25.850
[Stack Trace]:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/sagit/sagit:7.1.1/NMF26X/7.12.7:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 4492, tid: 4492, name: droid.ugc.aweme  >>> com.ss.android.ugc.aweme <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)'
    x0   0000000000000000  x1   000000000000118c  x2   0000000000000006  x3   0000007fa56d3da0
    x4   0000000000000000  x5   0000007fa56d3905  x6   0000007fa56d3905  x7   4c41433a5d4c454e
    x8   00000000000000f0  x9   0000007fa57b4aa0  x10  00000000000003e8  x11  0000000000000000
    x12  0000000005f5e100  x13  327981a46c559b81  x14  0000000000000000  x15  0011f832bc386d06
    x16  0000007f5da51e58  x17  0000007fa4716ed0  x18  327981a46c559b81  x19  0000007fa56d3da0
    x20  000000000000118c  x21  000000000000118c  x22  0000007f5da53000  x23  0000000000000000
    x24  0000007fa57b4b38  x25  0000000000000525  x26  0000007fa114b652  x27  0000007ff8067931
    x28  0000007fa11fc7c0  x29  0000007fa56d3d20  x30  0000007f5da42f4c
    sp   0000007fa56d3d00  pc   0000007fa4716ef0  pstate 0000000060000000

backtrace:
    #00 pc 000000000001bef0  /system/lib64/libc.so (syscall+32)
    #01 pc 0000000000004f48  /data/app/com.ss.android.ugc.aweme-1/lib/arm64/libnpth.so

**Comment by GangJust** [comment]
你可以试试lsp，没测试原版xposed，没设备

**Comment by berebrn** [comment]
> 你可以试试lsp，没测试原版xposed，没设备

好的，谢谢大佬！
