### ISSUE TITLE
[Bug反馈] 1.3.5起targetSdkVersion过低

### ISSUE THREAD

**Issue by klxiaoniu** [GangJust/FreedomPlus#112]
### 基本信息

设备信息：红米K50
系统版本：Android 14
模块框架：Lsposed
模块版本：Freedom+_1.3.6_141
应用版本：抖音_30.7.0_300701
应用ABI：64位

### 如何复现

从模块版本1.3.5起，模块的targetSdkVersion变成了24，以前是34。理论上无法在安卓14上直接安装（当然用root或者命令行添加参数可以），且打开模块主界面时系统会弹出旧版提示。

### 截图或视频

-

### 补充说明

其实不影响模块正常功能，只是感觉上不太舒服，期待修改。

### 崩溃堆栈文本信息

-

**Comment by GangJust** [comment]
https://github.com/GangJust/FreedomPlus/commit/cc835d75d8f5f61467413e0393d44aedebe37275
