### ISSUE TITLE
大佬能不能添加一些功能

### ISSUE THREAD

**Issue by a857112551** [GangJust/FreedomPlus#12]
1.自动播放下一条
2.视频流过滤：直播、图文、广告这些
3.长按功能，打开评论区
只是建议啊，建议啊，建议啊

**Comment by Lincope** [comment]
自动播放下一条抖音有这个功能 但每次打开默认都关闭
建议加个锁定自动播放下一条这个按钮

**Comment by Demon-Lucifer** [comment]
譬如隐藏加号后提供直接干掉加号组件的选项，还有评论区深色，这真的很重要😢

**Comment by monodevelop2020** [comment]
顶部和底部栏最好都能全部隐藏。
暂停时，可以显示文案及评论等内容。
