### ISSUE TITLE
保存表情包无法使用

### ISSUE THREAD

**Issue by BrezeSea** [GangJust/FreedomPlus#13]
保存表情包功能所保存的图片与原图片无关![Screenshot_2023-09-02-00-20-02-367_com.ss.android.ugc.aweme-edit.jpg](https://github.com/GangJust/FreedomPlus/assets/116472381/7efdce8b-8995-4e81-bdc2-29e76470412f)

![Screenshot_2023-09-02-00-22-21-226_com.miui.gallery.jpg](https://github.com/GangJust/FreedomPlus/assets/116472381/bb517168-9a22-405e-b5ec-9c1ec05fa248)

**Comment by GangJust** [comment]
测试的正常呀，

**Comment by BrezeSea** [comment]
> 测试的正常呀，

抖音版本24.4
保存表情包确实不行，保存图片可以

**Comment by GangJust** [comment]
24.4。。。。后续看情况修改

**Comment by BrezeSea** [comment]
> 24.4。。。。后续看情况修改

换了23.5也不行💦

**Comment by GangJust** [comment]
1.2.0更换了获取逻辑，试试看
