### ISSUE TITLE
大佬能做一个实名跳核模块吗？

### ISSUE THREAD

**Issue by LHC12580** [GangJust/FreedomPlus#15]

**Comment by GangJust** [comment]
什么意思？

**Comment by LHC12580** [comment]
就是抖音老是跳出来实名认证，想用另外手机号注册都不行，需要实名认证，很烦人



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 下午3:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GangJust/FreedomPlus] 大佬能做一个实名跳核模块吗？ (Issue #15)




 
什么意思？

**Comment by GangJust** [comment]
跳不了

**Comment by LHC12580** [comment]
为啥，需要团队才能破解吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 下午3:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GangJust/FreedomPlus] 大佬能做一个实名跳核模块吗？ (Issue #15)




 
跳不了
