### ISSUE TITLE
大佬能加一个抓包功能吗

### ISSUE THREAD

**Issue by p-hzc** [GangJust/FreedomPlus#17]
[大佬能加一个抓包模块吗](https://bbs.kanxue.com/thread-276015.htm)

**Comment by GangJust** [comment]
> [大佬能加一个抓包模块吗](https://bbs.kanxue.com/thread-276015.htm)

这个得对so层操作，xposed没有办法的

**Comment by p-hzc** [comment]
> > [大佬能加一个抓包模块吗](https://bbs.kanxue.com/thread-276015.htm)
> 
> 这个得对so层操作，xposed没有办法的

我这个标题有个链接点进去的是一篇文章  是hook的一个开关  不是对so层操作的  目前应该是可以用xposed hook的  附上两篇文章  大佬判断下能否实现不  https://bbs.kanxue.com/thread-268651.htm    https://bbs.kanxue.com/thread-276015.htm

**Comment by GangJust** [comment]
> > > [大佬能加一个抓包模块吗](https://bbs.kanxue.com/thread-276015.htm)
> > 
> > 
> > 这个得对so层操作，xposed没有办法的
> 
> 我这个标题有个链接点进去的是一篇文章 是hook的一个开关 不是对so层操作的 目前应该是可以用xposed hook的 附上两篇文章 大佬判断下能否实现不 https://bbs.kanxue.com/thread-268651.htm https://bbs.kanxue.com/thread-276015.htm

这个类和方法的确保留了，我晚上看看
