### ISSUE TITLE
抖音最新版27.2.0不支持，支持列表里有

### ISSUE THREAD

**Issue by huangzhitian** [GangJust/FreedomPlus#21]
模块显示已经加载，打开抖音有小弹窗，但左下角抖音没看到入口，大家在用什么版本

**Comment by GangJust** [comment]
抖音设置页底部版本号后是否有入口，是否开启了去插件化？开了就关掉。

**Comment by huangzhitian** [comment]
> 抖音设置页底部版本号后是否有入口，是否开启了去插件化？开了就关掉。
原来如此，关掉去插件化有入口了，但打开入口就报错了![Screenshot_20231009-081421_Freedom+.jpg](https://github.com/GangJust/FreedomPlus/assets/129321746/c1d9ac20-b018-494f-96c0-2086fd5b81a6)
