### ISSUE TITLE
[功能建议]首页控件消除+无水印下载按钮取消原复制功能

### ISSUE THREAD

**Issue by aidangaiguo230331** [GangJust/FreedomPlus#24]
### 功能建议

新功能建议

### 基本信息

设备信息：Redmi K50 Ultra
系统版本：Android 13
模块版本：Freedom+_com.freegang.fplus_1.2.2
应用版本：抖音_com.ss.android.ugc.aweme_270201
应用ABI：64位

### 功能描述

①首页控件消除：
对于首页空间点赞按钮，评论按钮，收藏按钮，不喜欢按钮或是分享按钮，自由选择透明度，透明度为0/-1即为隐藏，让此按钮直接在屏幕中消失，例如：我设置点赞按钮为-1，点赞按钮会在屏幕中消失，头像会自动接替原点赞按钮以不影响美观。

②无水印下载按钮取消原复制功能：
在点击无水印按钮（即为复制链接按钮）时，抑制原功能使其不会复制视频链接到剪贴板。或与可以把这个功能放到保存本地按钮里，也是抑制原功能，但是在新下载页面加一个有水印下载选项，以便用户自己更好的进行选择。

### 需要理由

①清爽模式太清爽了，我大部分时间会在刷视频的时候看看评论，99.9%不会进行点赞操作。希望进行有选择的清爽。

②在想要下载无水印视频的时候还会复制链接到剪贴板，有点影响操作。

**Comment by GangJust** [comment]
清爽模式长按菜单选项 【评论，收藏，分享】 的唤起就是避免在控件清空之后无法打开评论区的，如果按照现在你的逻辑来修改，那得推掉之前的逻辑进行重写了；另外复制链接这一块是因为之前走的是http接口去解析原视频，以至于在之后官方接口增加了`X-Bogus`无法直接调用了，即换成了代码获取，没修改复制链接这一步骤的操作逻辑(主要是因为懒)。

**Comment by GangJust** [comment]
新版本已经支持控件隐藏细化。
