### ISSUE TITLE
[Bug反馈]无法打开商品橱窗

### ISSUE THREAD

**Issue by zhu-mq** [GangJust/FreedomPlus#28]
### 基本信息

设备信息：小米10
系统版本：Android 11
模块版本：1.2.3
应用版本：24.4.0
应用ABI：64位

### 如何复现

所有人主页商品橱窗都打不开，点击没反应

### 截图或视频
https://github.com/GangJust/FreedomPlus/assets/119273751/a99c5042-d0de-4747-ac53-5c88e6bb2e83

### 补充说明

如果有其他补充，请在这里自由发挥。

### 崩溃堆栈文本信息

**Comment by GangJust** [comment]
进tg群测beta版
