### ISSUE TITLE
下载文件

### ISSUE THREAD

**Issue by 13903089240** [GangJust/FreedomPlus#29]
个别下载视频标题一样的话，前面下载的视频会被替换了，建议后面默认+个时间

**Comment by 13903089240** [comment]
> 个别下载视频标题一样的话，前面下载的视频会被替换了，建议后面默认+个时间



> 个别下载视频标题一样的话，前面下载的视频会被替换了，建议后面默认+个时间

**Comment by GangJust** [comment]
那不然加文本框是干嘛的呢？
