### ISSUE TITLE
透明度调整为0后没办法选中

### ISSUE THREAD

**Issue by jiangleixw** [GangJust/FreedomPlus#31]

**Comment by GangJust** [comment]
正常，为0后将默认不可用。

**Comment by jiangleixw** [comment]
明白，但是透明度为0且隐藏顶部选项后我想重新进入模块设置就没办法侧滑进入或者没办法选中左顶角的三个小横杠😂









我与旧事归于尽&nbsp;&nbsp;来年依旧笑春风

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月17日(周五) 中午12:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GangJust/FreedomPlus] 透明度调整为0后没办法选中 (Issue #31)




 
正常，为0后将默认不可用。

**Comment by GangJust** [comment]
下个版本取消禁用逻辑

**Comment by jiangleixw** [comment]
Hello，汇报一个错误反馈！


发生错误: Array index out of range: 1
出现时间: 2023-11-20 17:25:21.71
设备信息: Xiaomi M2011K2C
系统版本: Android 12 (31)
应用版本: 抖音 27.0.0 (270001)
应用架构: arm64
Google安全补丁级别: 2022-08-01
Dalvik虚拟机: instructionSet=arm64; is64Bit=true
堆栈信息: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
&nbsp;at android.util.ArrayMap.valueAt(ArrayMap.java:524)
&nbsp;at android.app.ActivityThread.collectComponentCallbacks(ActivityThread.java:5909)
&nbsp;at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:6499)
&nbsp;at android.app.ActivityThread.access$1400(ActivityThread.java:268)
&nbsp;at android.app.ActivityThread$ApplicationThread.lambda$scheduleTrimMemory$0(ActivityThread.java:1742)
&nbsp;at android.app.ActivityThread$ApplicationThread$$ExternalSyntheticLambda2.accept(Unknown Source:8)
&nbsp;at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:281)
&nbsp;at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:204)
&nbsp;at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
&nbsp;at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
&nbsp;at android.view.Choreographer.doCallbacks(Choreographer.java:946)
&nbsp;at android.view.Choreographer.doFrame(Choreographer.java:877)
&nbsp;at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
&nbsp;at android.os.Handler.handleCallback(Handler.java:938)
&nbsp;at android.os.Handler.dispatchMessage(Handler.java:99)
&nbsp;at android.os.Looper.loopOnce(Looper.java:210)
&nbsp;at android.os.Looper.loop(Looper.java:299)
&nbsp;at android.app.ActivityThread.main(ActivityThread.java:8118)
&nbsp;at java.lang.reflect.Method.invoke(Native Method)
&nbsp;at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
&nbsp;at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)











我与旧事归于尽&nbsp;&nbsp;来年依旧笑春风

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月17日(周五) 中午12:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GangJust/FreedomPlus] 透明度调整为0后没办法选中 (Issue #31)




 
下个版本取消禁用逻辑
