### ISSUE TITLE
[功能建议]点赞，头像，评论，文案等控件可单独设置透明度

### ISSUE THREAD

**Issue by mobai329** [GangJust/FreedomPlus#32]
新功能建议

### 功能描述
点赞，头像，评论，文案等空间可单独设置透明度；可单独隐藏点赞，评论等控件

### 需要理由
希望将视频控件透明度调整细化，让抖音纯粹刷视频

**Comment by GangJust** [comment]
新版本已经支持控件隐藏细化。
