### ISSUE TITLE
[Bug反馈]清爽模式异常。

### ISSUE THREAD

**Issue by 1316575628** [GangJust/FreedomPlus#42]
### 基本信息

设备信息：Redmi K50U
系统版本：Android 12
模块版本：Freedom+ 1.2.5
应用版本：抖音官版 28.1  28.4
应用ABI：64位

### 如何复现
什么都不开，只开清爽模式，然后暂停视频即可出现截图所示内容，有的时候还会自动切换倍速。

### 截图或视频

![Screenshot_2024-01-13-20-19-29-334_com ss android ugc aweme](https://github.com/GangJust/FreedomPlus/assets/48120931/a9e4cae3-04e6-49cd-ae94-017c70e9d4e5)
![Screenshot_2024-01-13-20-19-34-439_com ss android ugc aweme](https://github.com/GangJust/FreedomPlus/assets/48120931/dc1d5288-13e8-4c53-8c7c-92212214605a)
![IMG_20240113_202005](https://github.com/GangJust/FreedomPlus/assets/48120931/5fc8748f-97a1-42c9-afb1-e165006b67fa)

### 补充说明

如果有其他补充，请在这里自由发挥。

### 崩溃堆栈文本信息

如果能提供，请在这里填写崩溃堆栈文本信息。

**Comment by GangJust** [comment]
底部控制栏是新版抖音默认出现的东西，目前看来是云控的，下个版本会给个开关决定这个东西是否显示。

**Comment by GangJust** [comment]
1.2.6已支持自行隐藏底部控制栏
