### ISSUE TITLE
功能建议：希望添加三个新功能

### ISSUE THREAD

**Issue by freedomspiritJohn** [GangJust/FreedomPlus#43]
1 希望可以单独屏蔽界面上的组件，设置透明度或者直接进行单独屏蔽。[喜欢，评论，收藏，分享，文案，等]。
2希望可以在暂停视频的时候恢复界面的布局，恢复成没开插件之前的模样，这样方便进行别的操作
3希望可以长按视频打开评论区。
类似于抖音＋模块的功能。
![Screenshot_2024-01-11-01-07-29-549_com ss android ugc aweme](https://github.com/GangJust/FreedomPlus/assets/129288685/984d2cbc-2ba2-457e-8cf6-8a49484164c9)
![Screenshot_2024-01-11-01-10-09-744_com ss android ugc aweme](https://github.com/GangJust/FreedomPlus/assets/129288685/db209b19-03fb-41be-bcdf-409421d2df7d)

**Comment by GangJust** [comment]
打开评论区可自行设置双击响应事件；视频右侧控件屏蔽在beta版本已经有了，可以等待下个release；暂停恢复控件请打开清爽模式。

**Comment by freedomspiritJohn** [comment]
> 打开评论区可自行设置双击响应事件；视频右侧控件屏蔽在beta版本已经有了，可以等待下个release；暂停恢复控件请打开清爽模式。

😭，那能不能添加一个长按打开评论区的功能。

**Comment by GangJust** [comment]
你为何不试试普通模式+控件透明度调整？

**Comment by freedomspiritJohn** [comment]
> 你为何不试试普通模式+控件透明度调整？

不好意思，上次没生效，应该是和别的插件一起用的原因，今天试了一下可以了。[尴尬]
视频暂停的时候可以恢复隐藏的或者透明的控件吗，这样不仅能防烧屏，还能在想看视频的作者是否在直播和视频的点赞量评论数的时候暂停查看。希望懒羊羊大人可以考虑。
还有就是长按打开评论区真的挺方便的。

**Comment by GangJust** [comment]
那就只用清爽模式，别开透明度

**Comment by freedomspiritJohn** [comment]
> 那就只用清爽模式，别开透明度

好吧，谢谢大佬
