### ISSUE TITLE
【功能建议】清爽模式下能否隐藏状态栏？

### ISSUE THREAD

**Issue by emucno** [GangJust/FreedomPlus#45]
不想开启全屏沉浸，画面拉伸好多边上的文字看不到。

**Comment by XIU2** [comment]
我也有类似的想法，目前清爽模式下暂停会显示控件，根据这点，所以我就想如果可以清爽模式下 `暂停时显示状态栏`，`播放时隐藏状态栏` 就更好了，不过我和楼主不一样的是，我是 全屏沉浸+清爽模式（否则上下大黑边看着有点别扭。。）。

主要是隐藏状态栏后，看时间什么的就很不方便，如果可以实现上面我说的，那么想看时间的时候只需要暂停一下就行了，不用在用手去拨顶部状态栏了。。。

不过考虑到现在模块里设置显示/隐藏状态栏还需要重启抖音，可能这个需求难以实现吧。。。

**Comment by GangJust** [comment]
#23
