### ISSUE TITLE
［功能建议］评论区图片下载改进

### ISSUE THREAD

**Issue by Sunshinerainbowlittlehorse** [GangJust/FreedomPlus#46]
![Screenshot_20240126-151814_抖音](https://github.com/GangJust/FreedomPlus/assets/139889729/7bff5d18-a303-4e8e-a155-56cec190ac2a)
评论区图片的保存按钮被“我也发一张”的窗口挡住无法保存，建议更改按钮位置或者更改成长按保存图片

**Comment by GangJust** [comment]
新版抖音 “我也发一张” 在底部，所以之前的按钮间隔取消了，没考虑旧版本。
