### ISSUE TITLE
[bug反馈]部分图片无法预览

### ISSUE THREAD

**Issue by xingxinag** [GangJust/FreedomPlus#47]
设备信息：红米Note 11 tPro
系统版本：Android 13
模块版本：Freedom+ 1.2.6
应用版本：抖音28.6.0
应用ABI：  64位

Bug详情。
在抖音里用这个模块下载的图片或视频有很长的中文加英文加字符的命名，导致图片解析会出现莫名其妙的bug而且在电脑里面也无法预览。
![Screenshot_2024-01-26-15-44-12-812_com.android.fileexplorer.jpg](https://github.com/GangJust/FreedomPlus/assets/105782492/b178ff8d-1833-4a2e-a9fe-e03e7eee6ab3)

![Screenshot_2024-01-26-15-44-24-432_com.android.fileexplorer.jpg](https://github.com/GangJust/FreedomPlus/assets/105782492/4d57ecd6-8e23-4dfd-ab49-70f5e4a7d421)

![屏幕截图 2024-01-26 154714.png](https://github.com/GangJust/FreedomPlus/assets/105782492/c74d9c95-b645-4ca6-8a29-dc71b837fcdf)

![IMG_20240126_154356.jpg](https://github.com/GangJust/FreedomPlus/assets/105782492/c6977bec-2166-4c21-bbd7-82b9757eb5c0)

![屏幕截图 2024-01-26 154518.png](https://github.com/GangJust/FreedomPlus/assets/105782492/bb17ec40-c3ef-476c-bd37-f1e9c47013d9)

![屏幕截图 2024-01-26 154622.png](https://github.com/GangJust/FreedomPlus/assets/105782492/642c8035-1192-4318-8374-9665d245bfc1)

**Comment by GangJust** [comment]
#22

**Comment by xingxinag** [comment]
啊啊啊![filesbfa2b607be0e1938c84f6c64b13faa1d.GIF](https://github.com/GangJust/FreedomPlus/assets/105782492/596d2ebc-bbcb-42ce-b09d-976ee524b6bc)

**Comment by GangJust** [comment]
> 啊啊啊![filesbfa2b607be0e1938c84f6c64b13faa1d.GIF](https://private-user-images.githubusercontent.com/105782492/299918132-596d2ebc-bbcb-42ce-b09d-976ee524b6bc.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTgyMTIsIm5iZiI6MTcwNjI1NzkxMiwicGF0aCI6Ii8xMDU3ODI0OTIvMjk5OTE4MTMyLTU5NmQyZWJjLWJiY2ItNDJjZS1iMDlkLTk3NmVlNTI0YjZiYy5HSUY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwODMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmNmNzYwM2Y5Nzg4NTJjMWIxNThmMDZjZDNiOTdiMTMwZjU4MWQzMTE4MmU4YmM0NWZhY2MzYWNjYjUwMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LDo_8d_jGWw8GmlElZxdt2BWK1qmLh6w3IAMvzWd6Ws) [ ![filesbfa2b607be0e1938c84f6c64b13faa1d.GIF](https://private-user-images.githubusercontent.com/105782492/299918132-596d2ebc-bbcb-42ce-b09d-976ee524b6bc.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTgyMTIsIm5iZiI6MTcwNjI1NzkxMiwicGF0aCI6Ii8xMDU3ODI0OTIvMjk5OTE4MTMyLTU5NmQyZWJjLWJiY2ItNDJjZS1iMDlkLTk3NmVlNTI0YjZiYy5HSUY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwODMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmNmNzYwM2Y5Nzg4NTJjMWIxNThmMDZjZDNiOTdiMTMwZjU4MWQzMTE4MmU4YmM0NWZhY2MzYWNjYjUwMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LDo_8d_jGWw8GmlElZxdt2BWK1qmLh6w3IAMvzWd6Ws) ](https://private-user-images.githubusercontent.com/105782492/299918132-596d2ebc-bbcb-42ce-b09d-976ee524b6bc.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTgyMTIsIm5iZiI6MTcwNjI1NzkxMiwicGF0aCI6Ii8xMDU3ODI0OTIvMjk5OTE4MTMyLTU5NmQyZWJjLWJiY2ItNDJjZS1iMDlkLTk3NmVlNTI0YjZiYy5HSUY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwODMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmNmNzYwM2Y5Nzg4NTJjMWIxNThmMDZjZDNiOTdiMTMwZjU4MWQzMTE4MmU4YmM0NWZhY2MzYWNjYjUwMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LDo_8d_jGWw8GmlElZxdt2BWK1qmLh6w3IAMvzWd6Ws) [ ](https://private-user-images.githubusercontent.com/105782492/299918132-596d2ebc-bbcb-42ce-b09d-976ee524b6bc.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTgyMTIsIm5iZiI6MTcwNjI1NzkxMiwicGF0aCI6Ii8xMDU3ODI0OTIvMjk5OTE4MTMyLTU5NmQyZWJjLWJiY2ItNDJjZS1iMDlkLTk3NmVlNTI0YjZiYy5HSUY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNlQwODMxNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmNmNzYwM2Y5Nzg4NTJjMWIxNThmMDZjZDNiOTdiMTMwZjU4MWQzMTE4MmU4YmM0NWZhY2MzYWNjYjUwMGQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LDo_8d_jGWw8GmlElZxdt2BWK1qmLh6w3IAMvzWd6Ws)

。。。也不一定是文件名的问题，你尝试自定义文件名试试，看是否还是同样的几张图片无法预览？当然也不排除可能是请求链过期或者下发的图片原始数据出问题了，我刚尝试了几个，并没有出现类似的问题。

**Comment by GangJust** [comment]
> 我已经尝试过自定义文件名了，但是还是无法预览，用这个模块下载的图片都是无法预览。然后我又换成了解析软件。下载的同样图片，同一链接。却可以预览。

分享一下链接，我看看呢？

**Comment by xingxinag** [comment]
5.38 复制打开抖音，看看【我的书单日记的图文作品】世人皆知李清照，无人知我鱼玄机 她笔下的哪句诗最触... https://v.douyin.com/iLbaAFHx/ NWm:/ 07/06 x@F.Uy

**Comment by xingxinag** [comment]
你这下载的放到电脑上可预览？😨😨😨😨😨😨你点开图片，然后点详情看一下。是不是也是好多中文乱七八糟的字符命名的。

**Comment by GangJust** [comment]
这里的命名格式为：作者名_账号_文案_编号。
![image](https://github.com/GangJust/FreedomPlus/assets/30917584/aa7f0f2b-51f2-4f04-be43-fe18585b7e8f)

![image](https://github.com/GangJust/FreedomPlus/assets/30917584/19bfcda2-7572-4e29-b9b8-74e5d3bd6aa0)

**Comment by xingxinag** [comment]
好叭，那应该是别的问题吧。😊辛苦老哥了。
