### ISSUE TITLE
视频下载失效

### ISSUE THREAD

**Issue by clock8863** [GangJust/FreedomPlus#49]
现在点复制链接会出现领红包页面。![Screenshot_2024-02-07-11-02-36-049_com.ss.android.ugc.aweme.jpg](https://github.com/GangJust/FreedomPlus/assets/113651907/3abd3513-192d-4439-8399-8700d2e3805e)

**Comment by GangJust** [comment]
![Screenshot_2024-02-07-11-19-13-906_com ss android ugc aweme-edit](https://github.com/GangJust/FreedomPlus/assets/30917584/9ab3a8a4-fc5a-40be-80af-7fa6fd32e8cc)
