### ISSUE TITLE
jniLibs无需手动添加libdexkit.so

### ISSUE THREAD

**Issue by teble** [GangJust/FreedomPlus#5]
引入maven包后打包的时候不应该自动会把so打包进apk吗，~~感觉这样后续dexkit依赖版本更新会出问题~~
![image](https://user-images.githubusercontent.com/33313113/236441360-1e4f977c-1925-4f62-afd6-252e6843a72c.png)

**Comment by GangJust** [comment]
感谢大佬提醒，测试的时候忘删了😝!
