### ISSUE TITLE
[Bug反馈]更新最新版抖音后模块设置入口消失

### ISSUE THREAD

**Issue by CaterMaoZi** [GangJust/FreedomPlus#50]
设备信息：LG-G8
系统版本：原生Android 12
模块框架：Lsposed
模块版本：1.2.6
应用版本：28.7.0
应用ABI：64位

_抖音开发者信息:
UserId: 3705777613199320
DeviceId: 3802583917134044
UpdateVersionCode: 28709900
Channel: update
GitSHA: 200969ece72
VESDK: 15.8.1.1
EffectSdk: 15.8.0_rel_699_douyin_202401231050_e7becb40f14
CloudAlbumSdk: 5.0.0
ILASDK: 1.6.0-rc.3.1-bugfix
LiveCore: 15.5.0.131
v28.7.0 Build update_200969e_20240129_9fc5b11e-bea1-11ee-b68a-d6a8b39575a5
VmsdkAndroid: 2.5.4-worker
HostAbi: arm64-v8a(64 bit)TTNetVersion: 4.2.137.40-douyin
MicroAppVersionCode: 28709008_

视频:
https://github.com/GangJust/FreedomPlus/assets/126097270/9f5088bc-f72b-44e1-83c7-c67828c20a98

**Comment by GangJust** [comment]
模块没生效，生效状态下启动时会有一个 "Freedom+ Attach!" 的底部 Toast

**Comment by CaterMaoZi** [comment]
> 模块没生效，生效状态下启动时会有一个 "Freedom+ Attach!" 的底部 Toast

现在进入会显示Freedom+ Attach!了 但还是没有模块入口 功能也不生效

**Comment by GangJust** [comment]
模块app能跳转设置页么？不能的话清除抖音数据试试？

**Comment by CaterMaoZi** [comment]
> 模块app能跳转设置页么？不能的话清除抖音数据试试？

再次更新到最新版模块后，清除了模块的数据重新打开，点模块设置能成功打开，功能也能生效，但是抖音内没有入口只能从模块打开

**Comment by GangJust** [comment]
侧滑设置应该是不会马上出来的，要等待云控数据加载完后才出现，你试试多重启几次抖音？

**Comment by CaterMaoZi** [comment]
> 侧滑设置应该是不会马上出来的，要等待云控数据加载完后才出现，你试试多重启几次抖音？

重启了不管用 可能是因为我抖音app装在sd卡里的原因?

**Comment by GangJust** [comment]
莫名奇妙的问题，侧滑栏需要触摸滑动才会出现设置项，或者提供一下lsp的日志？另外清爽模式开关打开后可通过长按视频上/下部分进入模块设置页。

**Comment by CaterMaoZi** [comment]
> 莫名奇妙的问题，侧滑栏需要触摸滑动才会出现设置项，或者提供一下lsp的日志？另外清爽模式开关打开后可通过长按视频上/下部分进入模块设置页。

移出sd卡后已经可以正常使用

**Comment by CaterMaoZi** [comment]
tks
