### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by ajin-ajinna** [GangJust/FreedomPlus#51]
### 功能建议

新功能建议

### 基本信息

设备信息：华为P60
系统版本：Android 12
模块版本：Freedom+_1.2.6
应用版本：抖音_28.6.0
应用ABI：64位

### 功能描述

去除推荐页面或启动启动首页由推荐改为关注

### 需要理由

不想看推荐，只想看一些自己关注的内容

**Comment by GangJust** [comment]
意义不大，真就不能动手点一次？
