### ISSUE TITLE
28.7.0版本复制链接后无下载按钮

### ISSUE THREAD

**Issue by Winyer** [GangJust/FreedomPlus#52]
是Bug还是没支持呢？

**Comment by GangJust** [comment]
![image](https://github.com/GangJust/FreedomPlus/assets/30917584/5219266e-f546-431b-8c0d-256cd10ee0ae)

**Comment by Winyer** [comment]
抱歉，才开始用这个不清楚，难怪我找了半天没找到😂，还有其他方式可以下载吗

**Comment by GangJust** [comment]
模块设置页打开清爽模式开关，长按屏幕下半可唤起下载弹窗
