### ISSUE TITLE
下载图片BUG

### ISSUE THREAD

**Issue by Saulwonderfulman** [GangJust/FreedomPlus#71]
在下载图片时,如果发布者有多张图片有可能会在下载到第某张照片时卡住,此时如果按返回或者直接关掉抖音,则已经下载的图片删除后会在再次打开抖音后重新出现,也即图片删不掉

在重装抖音也无法恢复,希望可以早日修复

**Comment by GangJust** [comment]
多次测试，并未复现，请详细描述 #22
