### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by 008s** [GangJust/FreedomPlus#72]
模块用着很好用，可否再优化一下清爽模式下刷视频隐藏周边控件的速度呢？

**Comment by GangJust** [comment]
控件的隐藏是根据视频的播放状态来的，因为在逻辑上要对视频的暂停做控件的显示，而视频在缓冲和加载下并不属于播放状态，所以这种情况没办法；要么就是还原一开始的逻辑，清爽模式不论视频播放暂停与否都不做控件的展示。

**Comment by 008s** [comment]
好吧，很感谢你的答复。
