### ISSUE TITLE
[BUG 反馈] 最新 v1.3.0 版本 双击打开评论 功能会同时点赞视频

### ISSUE THREAD

**Issue by XIU2** [GangJust/FreedomPlus#74]
### 基本信息

设备信息：红米 K60
系统版本：Android 13
模块框架：Lsposed
模块版本：FreedomPlus 1.3.0
应用版本：抖音 23.5.0
应用ABI：64位

### 如何复现

1.3.0 版本下，双击视频时，打开评论的同时依然还点赞视频了。
另外长按视频下半部分也开始弹出官方菜单了（就是分享、不感兴趣等等功能的那个菜单），之前是正常的，这是我看到 1.2.9 版本的更新日志里有 `修复清爽模式长按偶弹官方菜单问题` 时，顺便测试的。

我是从 1.2.8 版本升级上来后发现的，我刚才又测试了下 1.2.9 版本，发现干脆就打不开抖音了（开屏界面 100% 闪退），所以不确定该问题是不是 1.2.9 版本的更新引起的。

****

另外，在 1.2.8 版本及之前版本，我就遇到了 双击打开评论 功能的相关问题，即双击视频打开评论时也会弹出官方菜单（就是分享、不感兴趣等等功能的那个菜单），只有双击视频的部分位置时才不会弹出官方菜单（例如清爽模式下的底部进度条及下方区域，以及两侧长按倍速的区域，但会导致打开评论区时也触发持续的倍速播放模式），因此凑活着也能用我就没提反馈。

我也搜过 Issues 发现根本没人提这个，我就比较纳闷难道只有我遇到了？我当时也测试过了新版本抖音，也存在上述问题（当然只是上面我说的 "另外" 后内容我进行了抖音新版本测试）。

### 截图或视频

无

### 补充说明

无

### 崩溃堆栈文本信息

无

**Comment by GangJust** [comment]
1.2.9之后双击点赞问题应该是类缓存未更新造成的，可以尝试进入模块设置页点击顶部图标按钮清除类缓存，待下次运行时，模块会重新对相关功能类进行搜索缓存；另外关于崩溃问题，官方貌似在部分机型上会频繁出现控件空指针崩溃的情况，模块设置页最底部增加了崩溃容错的选项，可以尝试打开。

**Comment by XIU2** [comment]
那个 清理类日志 功能我昨天晚上试过了也不行，依然还是会点赞。
我目前是退回 1.2.8 版本并再次清理类日志，才能像以前那样双击部分位置来打开评论（双击其他位置依然会弹出官方菜单）

至于崩溃问题，目前只存在于 1.2.9 版本，这个版本下抖音是完全打不开的，哪怕我从 FreedomPlus 应用界面点击模块设置来打开跳转到抖音中的模块设置界面也是打不开的（开屏加载界面一两秒就闪退了）。。。自然无法开启 崩溃容错 选项，不过 1.3.0 版本就正常了。

**Comment by GangJust** [comment]
你的意思是 1.3.0 清爽模式弹窗仍会显示官方菜单？另外双击评论仍会点赞？你的抖音版本多少？28.0.0以下可能存在不兼容的问题。

**Comment by GangJust** [comment]
哦，我看到了你提供的抖音版本号 23.5.0，因为我在作最新逻辑的时候是基于28.0.0的，没再做低版本的适配了，毕竟抖音的更新频率为周更。

**Comment by GangJust** [comment]
我只能尽量保证最近三个大版本号的功能正常使用，当然如果抖音在大逻辑上有改动，可能需要重新找相关逻辑

**Comment by XIU2** [comment]
好吧，因为我只是单纯看抖音，不想用臃肿的新版（对于国内这些臃肿的 APP 我向来都是能用多低就多低，除非功能缺失没办法否则不会升级到新版本，而对于其他普通 APP 我一般会追求最新版本），因此一直用的是旧版本，在用 FreedomPlus 之前我用的抖音版本更低（谷歌港版 还是 16.4.X）。。
为了用 FreedomPlus 我特意升级到了 23.5.0 这个最低要求，相比其他还在更新的抖音模块，FreedomPlus 已经是抖音版本要求最低的了（而且还是少有开源的）。

既然这样，那我只能停留在 1.2.8 版本了，不过好在我对其他功能要求不高，更不更新影响不大~
