### ISSUE TITLE
使用log打印日志，logcat无输出

### ISSUE THREAD

**Issue by yyyyxvdasd** [GangJust/FreedomPlus#82]
不知道是不是抖音屏蔽了，调用Log.i后logcat没有日志输出

**Comment by GangJust** [comment]
是？什么意思？项目跑起来没有log？尝试清理clear几次日志面板，然后按tag过滤，某些时候设备刚连上logcat会有大量的log输出，这时候一般看不到log，可以等待几秒钟之后再尝试clear。

**Comment by yyyyxvdasd** [comment]
![1111](https://github.com/GangJust/FreedomPlus/assets/11845610/c6ddaea3-eefe-42c9-a086-13dacafbb156)
![222](https://github.com/GangJust/FreedomPlus/assets/11845610/b2099f17-f0e5-4347-a098-435db63eb38f)
![3333](https://github.com/GangJust/FreedomPlus/assets/11845610/503e64b9-8b86-4bea-99c8-b92e1c467655)
就是application创建后调用Log，logcat没有日志输出，抖音版本27.5.0，不知道是不是抖音拦截了

**Comment by yyyyxvdasd** [comment]
你那边这样调用有日志输出的吗

**Comment by GangJust** [comment]
不清空面板，重新选择一下设备呢？
![image](https://github.com/GangJust/FreedomPlus/assets/30917584/82275903-95fb-4230-baf2-3e25ab55a3b9)

**Comment by GangJust** [comment]
重新选择设备，即可
![image](https://github.com/GangJust/FreedomPlus/assets/30917584/811d0fb0-514e-4729-bfd9-a322f26c4693)

**Comment by yyyyxvdasd** [comment]
还是没呀，大佬你的抖音是什么版本的

**Comment by yyyyxvdasd** [comment]
![4444](https://github.com/GangJust/FreedomPlus/assets/11845610/e41de6e8-c125-4eef-9b32-e1318151fb30)
![5555](https://github.com/GangJust/FreedomPlus/assets/11845610/373c96f3-b48f-4ac1-9912-585e62f7f3b9)
用24.1.0和最新的抖音没问题，就那个27.5.0的包有问题，不纠结了谢谢大佬
