### ISSUE TITLE
为什么左下角的推荐有时间有有时候没有

### ISSUE THREAD

**Issue by x3340804438** [GangJust/FreedomPlus#89]
如标题所示![Screenshot_2024-06-25-12-51-57-218_com.ss.android.ugc.aweme.jpg](https://g![Screenshot_2024-06-25-12-52-37-134_com.ss.android.ugc.aweme.jpg](https://github.com/GangJust/FreedomPlus/assets/153149136/fe7c168c-f548-423e-b42b-4d95beab6b42)

8922b8a9)

![正在上传 Screenshot_2024-06-25-12-52-37-134_com.ss.android.ugc.aweme.jpg…]()

**Comment by GangJust** [comment]
你应该去询问抖音官方，而不是这里。
