### ISSUE TITLE
lspatch内置的模块怎么唤出菜单啊

### ISSUE THREAD

**Issue by 3Kzpf** [GangJust/FreedomPlus#9]

**Comment by GangJust** [comment]
主页->左侧侧滑菜单->滑动到底部，换出模块设置；开启清爽模式开关后，长按视频上半/下半唤起清爽模式菜单(有反应长按无效的)

**Comment by Aurora-Simba** [comment]
![Screenshot_2023-07-06-16-17-59-07_2332cb9b27b851b548ba47a91682926c.jpg](https://github.com/GangJust/FreedomPlus/assets/106955617/b2b32328-cce2-46ab-a5c8-c6b45c5ac4fc)

没有模块菜单啊

**Comment by GangJust** [comment]
![image](https://github.com/GangJust/FreedomPlus/assets/30917584/b4dc8b83-5a3d-4a25-b086-cbeb128ef1e5)

**Comment by Aurora-Simba** [comment]
我都不知道为什么，估计是被云控了，只有搜索按钮，没有三条横杠

**Comment by tonynesss** [comment]
> ![image](https://github.com/GangJust/FreedomPlus/assets/30917584/b4dc8b83-5a3d-4a25-b086-cbeb128ef1e5)
> 

首页是个加号😂![Screenshot_2023-08-04-14-54-00-044_com.ss.android.ugc.aweme.jpg](https://github.com/GangJust/FreedomPlus/assets/32998682/81d7ccee-8248-4dc1-bea3-cc9f0fb888ef)
