### ISSUE TITLE
抖音30.4.0失效

### ISSUE THREAD

**Issue by actforjason** [GangJust/FreedomPlus#91]
评论区颜色模式没起作用

**Comment by TitoemX** [comment]
30.5.0亦失效

**Comment by GangJust** [comment]
33.4.0（含）之后，抖音重构了评论区，已经移除掉了深色逻辑（或者说他们并未增加深色逻辑），模块不会去自实现深色逻辑，一是麻烦，二是耗时又耗力，不用反馈。
