### ISSUE TITLE
1.33打开设置提示错误

### ISSUE THREAD

**Issue by ucxl** [GangJust/FreedomPlus#95]
错误信息: Only VectorDrawables and rasterized asset types are supported ex. PNG, JPG, WEBP
出现时间: 2024-07-06 09:33:07.34
设备信息: samsung SM-G9980
系统版本: Android 14 (34)
应用版本: 抖音 30.3.0 (300301)
应用架构: arm64
Google安全补丁级别: 2024-04-01
Dalvik虚拟机: instructionSet=unknown; is64Bit=true
堆栈信息: java.lang.IllegalArgumentException: Only VectorDrawables and rasterized asset types are supported ex. PNG, JPG, WEBP
	at o000000.OooO0O0.OooO00o(SourceFile:1015)

**Comment by GangJust** [comment]
#94
